### ISSUE TITLE
Update Lodash to >= 4.17.5 to avoid npm security alert about prototype pollution

### ISSUE THREAD

**Issue by revelt** [mozfreddyb/eslint-plugin-no-wildcard-postmessage#4]
hi! It seems that our `lodash` dependency is not up to date and according to `npm audit`, it has a "Low severity vulnerability":

<img width="663" alt="no-wildcard-postmessage" src="https://user-images.githubusercontent.com/8344688/44311716-55134f80-a3e4-11e8-8330-507f36fef00e.png">

Let's update the `lodash` dependency to the latest!

**Comment by mozfreddyb** [comment]
This plugin does not use lodash in itself. Could you help me find out which of the dependencies need updating (and to which version), so they stop using the affected lodash version?

**Comment by revelt** [comment]
Sorry, I worded the thing incorrectly. Yes, there's no `lodash` among deps but there's outdated `eslint`, `v.3.15.0` and I think that's what's causing trouble. The latest `eslint` is `5.4.0`, two majors above!

**Comment by mozfreddyb** [comment]
yeah, updating to a new eslint version needs a bit of plumbing and rewriting, since the API changed. I don't use this plugin myself, so I'm hesitant to spending too much time on this. I've filed issue #5 for this and happy to mentor.

**Comment by mozfreddyb** [comment]
The issue you report here here doesn't come from eslint though, the mocha test library (a dev dependency) uses lodash.
Given this is a *low* rated vulnerability *in tests* that doesn't affect the users of the plugin I don't think this has a high priority.

**Comment by revelt** [comment]
thanks! closing
